### ISSUE TITLE
fix font for body

### ISSUE THREAD

**Issue by maelle** [cynkra/cynkrablog#14]
is it supposed to not be light @christophsax?

**Comment by christophsax** [comment]
It should be 'light', but what we have in cynkrablog is 'thin' (despite the naming). Light ist what we have in cynkraweb.

cynkraweb:
<img width="624" alt="image" src="https://github.com/cynkra/cynkrablog/assets/1390827/b181e2cb-5d2e-4734-81e6-6e7d45f6d4fc">

cynkrablog:
<img width="348" alt="image" src="https://github.com/cynkra/cynkrablog/assets/1390827/fe6d6bf6-c79e-4aa1-93e2-9c920c036e04">

**Comment by maelle** [comment]
I'm not sure I follow... Does it mean the css rule loading the font is wrong?

**Comment by christophsax** [comment]
Yes, the css rule is wrong. 

I think I renamed the thin font to light at pre-historic times, to save 2 seconds instead of doing it properly. The fonts you are using in cynkrablog is 'frutiger-thin', but it wrongly calls itself 'frutiger-light'. The font that is used in cynkraweb is the true 'frutiger-light', and is thicker than 'frutiger-thin'. We want to use 'frutiger-light', the same font (and CSS) as in cynkraweb.

**Comment by maelle** [comment]
so https://github.com/cynkra/cynkratemplate is wrong too then?

**Comment by christophsax** [comment]
<img width="845" alt="image" src="https://github.com/cynkra/cynkrablog/assets/1390827/efed84c3-bf38-4cbb-9695-ac1d5b3485c6">

No, we are using either medium or book, something *thicker* than on the website.

<img width="845" alt="image" src="https://github.com/cynkra/cynkrablog/assets/1390827/cae90ea9-2256-47e1-8155-d0856e21061e">

**Comment by maelle** [comment]
I changed the rules in https://github.com/cynkra/cynkrablog/blob/main/custom.scss

**Comment by christophsax** [comment]
Very nice!
