### ISSUE TITLE
bold items in sidebar have too big bottom margin

### ISSUE THREAD

**Issue by maelle** [cynkra/cynkrablog#51]
![image](https://github.com/cynkra/cynkrablog/assets/8360597/a762b6ef-10e2-4447-8306-719229668443)

**Comment by talpitoo** [comment]
After the initial investigation this seems to be due to the font face itself: as if the font author wasn't careful enough  with the font metrics. The CSS properties are all the same (font face, weight, style, line-height, etc.) and it is happening with the original `.ttf` file as well.

I am going to further investigate the issue with e.g. FontForge but it is happening on the main cynkraweb site as well. This can be an aesthetic issue in the future, cc. @christophsax

**Comment by christophsax** [comment]
I reeeeeaaaaaally don't like faux bold. 

We have some other bold versions of the font somewhere, such as Frutiger Book. Will take a look, these fonts cost enough. Seems to affect lines with bold as well:

<img width="892" alt="image" src="https://github.com/cynkra/cynkrablog/assets/1390827/a1121746-36f6-424c-b223-7ceb31fc81c8">

Perhaps very naive, but why can't we just increase the overall line space to the one that's produced by the bold font?

**Comment by talpitoo** [comment]
From a technical/developer/outsider perspective it might seem silly but i understand/respect now that Frutiger is part of the Swiss national identity (just learnt that from https://en.wikipedia.org/wiki/Frutiger_(typeface)). In that case we have to find a solution for faux bold but 

1) changing the line height would be opening Pandora's box (either line-height or a CSS hack for the missing cap-size alignment, all in percentages, those roundings might be different for every font size, multiplied by different OS, browser, retina/DPI, etc.)

- https://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align
- https://seek-oss.github.io/capsize/

2) Since the slightly different line height is not noticeable for static bold text (e.g. where a few words or a link is bold in a longer sentence), it is present at the moment only in the blog's sidebar because there we change bold/normal back and forth on click. How about using a different style for highlighting the active blog category (e.g. underline, inverted background, cynkra blue or similar)?

**Comment by talpitoo** [comment]
> I reeeeeaaaaaally don't like faux bold 🤪

@christophsax okay, noted, please see the other possible solutions above.

**Comment by christophsax** [comment]
Suggested solution 2 sounds very good to me, and closer to what we have on cynkraweb - there we use color to highlight what is selected:

<img width="559" alt="image" src="https://github.com/cynkra/cynkrablog/assets/1390827/92e1e244-a441-4429-bce4-94932948ae08">

So looking for a different bold font is a task for after 2030 — very happy with that 😅

**Comment by talpitoo** [comment]
Okay, in that case we are going to keep Frutiger Bold (in general) but refactor the blog categories highlighting with a different color. I am going to proceed this way.

**Comment by talpitoo** [comment]
I have used an additional underline to make the highlighted state more prominent.
