### ISSUE TITLE
Fast rerendering

### ISSUE THREAD

**Issue by krlmlr** [cynkra/cynkrablog#60]
I'd like a successful `quarto render` to establish a state where a second `quarto render` finishes instantaneously. Is this possible?

CC @DivadNojnarg @maelle.

**Comment by maelle** [comment]
For computational chunks we have https://github.com/cynkra/cynkrablog/blob/097480475fb3e545bda674229e04db99aa7571d4/_quarto.yml#L13 see https://quarto.org/docs/projects/code-execution.html#freeze

Now instead of `quarto render` I think you should be using `quarto preview`. https://quarto.org/docs/tools/text-editors.html#workflow
